set(CMAKE_SYSTEM_NAME $ENV{BUILDER_OS})
set(CMAKE_SYSTEM_PROCESSOR $ENV{BUILDER_ARCH})

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_SYSROOT $ENV{GITHUB_WORKSPACE}/$ENV{BUILDER_TARGET_TRIPLE})
set(CMAKE_C_COMPILER_TARGET $ENV{BUILDER_TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET $ENV{BUILDER_TARGET_TRIPLE})
set(CMAKE_C_FLAGS -fPIC)
set(CMAKE_EXE_LINKER_FLAGS -fPIC)
set(CMAKE_EXE_LINKER_FLAGS -stdlib=libc++ -fuse-ld=lld)
set(LLVM_ENABLE_LIBCXX true)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
